FROM node:18-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY prisma ./prisma/
RUN npx prisma generate

COPY . .

EXPOSE 8000

CMD ["sh", "-c", "npx prisma generate && npx prisma migrate deploy && npm run dev"]

